linux:
  vars:
    ansible_ssh_private_key_file: "{{ ssh_key_path }}"
  hosts:
    networkingctrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    networkingwrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    networkingwrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"

vms:
  hosts:
    networkingctrl:
    networkingwrkr0:
    networkingwrkr1:

controllers:
  hosts:
    networkingctrl:

workers:
  hosts:
    networkingwrkr0:
    networkingwrkr1:
