linux:
  hosts:
    networkingctrl:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ control_plane_ip }}"
    networkingwrkr0:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[0] }}"
    networkingwrkr1:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[1] }}"
    networkingwrkr2:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[2] }}"
    networkingwrkr3:
      ansible_user: "{{ ssh_user }}"
      ansible_host: "{{ worker_ips[3] }}"
    #networkingwrkr4:
    #  ansible_user: "{{ ssh_user }}"
    #  ansible_host: "{{ worker_ips[4] }}"

vms:
  hosts:
    networkingctrl:
    networkingwrkr0:
    networkingwrkr1:
    networkingwrkr2:
    networkingwrkr3:
    #networkingwrkr4:

controllers:
  hosts:
    networkingctrl:
  
workers:
  hosts:
    networkingwrkr0:
    networkingwrkr1:
    networkingwrkr2:
    networkingwrkr3:
    #networkingwrkr4: